apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v2
  namespace: default
data:
  database.url: https://mydatabaseserver-v2.somewhere.com:3306
  database.password: P@SSW0rd1
