apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v3
  namespace: default
data:
  DATABASE_URL: https://mydatabaseserver-v2.somewhere.com:3306
  DATABASE_PASSWORD: P@SSW0rd1
